const express=require('express');
const router=express.Router();
const UserController=require('../controllers/usercontroller');
const upload=require('../middleware/upload');
const post=require('../middleware/post');
const reel=require('../middleware/reel');
router.post('/register',UserController.registerUser);
router.post('/login',UserController.loginUser);
router.post('/posts',post.single('image'),UserController.posts);
router.post('/addProfile',upload.single('profilePicture'),UserController.addProfile);
router.get('/posts',UserController.getAllPosts);
router.put('/posts/:id/like',UserController.likePost);
router.post('/posts/:id/comment',UserController.addComment);
router.post('/users/follow',UserController.followUser);
router.put('/posts/:id/caption',UserController.updateCaption);
router.delete('/posts/:postId/comment/:commentId',UserController.deleteComment);
router.post("/uploadReel", reel.single("reel"), UserController.uploadReel);
router.get("/reels", UserController.getAllReels);
router.post("/:id/like", UserController.likeReel);
router.post("/:id/comment", UserController.commentOnReel);
router.get('/messages/:userId/:friendId', UserController.getMessages);
router.get('/user/:id',UserController.fetchUser);
router.get("/followers/:userId", UserController.getFollowers);
module.exports=router;